### ISSUE TITLE
Feature Request: Ability to enable/disable LLM generation of chunk summary/title

### ISSUE THREAD

**Issue by tarockey** [microsoft/rag-experiment-accelerator#187]
Currently, the system uses an LLM to generate a Title and Summary for every document chunk, which is useful for a more powerful search index. However, when running at scale, it can take a very long time to generate all of that content. 

For quick iteration in testing other hyperparameters, ideally this feature could be toggled off, to reduce iteration time via the config.

**Comment by guybartal** [comment]
already done in [https://github.com/microsoft/rag-experiment-accelerator/pull/354](https://github.com/microsoft/rag-experiment-accelerator/pull/354 )
