### ISSUE TITLE
Disable forked repos from modifying github workflows

### ISSUE THREAD

**Issue by joshuaphelpsms** [microsoft/rag-experiment-accelerator#291]
We shouldn't allow outside contributors from modifying github workflows once the repo goes public. I don't think this is an issue while it is private since we can control who has access to the repo

see docs for how to fix: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories

**Comment by julia-meshcheryakova** [comment]
Checked: it is already fixed in settings.
