### ISSUE TITLE
[Bug] Semantic search is not enabled for this service.

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#329]
When trying to query using `search_for_match_semantic` `search_type` while `Semantic ranker` plan is not selected in Azure Search you will hit the following error:

> ERROR - rag_experiment_accelerator.search_type.acs_search_methods - (FeatureNotSupportedInService) Semantic search is not enabled for this service.
> Parameter name: queryType
> Code: FeatureNotSupportedInService
> Message: Semantic search is not enabled for this service.
> Parameter name: queryType
> Exception Details:      (SemanticQueriesNotAvailable) Semantic search is not enabled for this service.
>         Code: SemanticQueriesNotAvailable
>         Message: Semantic search is not enabled for this service.

Solution: Validate service tier before starting and fail fast

**Comment by ZikeiWong** [comment]
When running the following code
```python
results = search_client.search(  
    search_text=search_text,  
    query_type=QueryType.SEMANTIC,  
    semantic_configuration_name='my-semantic-config'  
)  
```
I also encountered this error:
```
azure.core.exceptions.HttpResponseError: (FeatureNotSupportedInService) Semantic search is not enabled for this service.
Parameter name: queryType
Code: FeatureNotSupportedInService
Message: Semantic search is not enabled for this service.
Parameter name: queryType
Exception Details:      (SemanticQueriesNotAvailable) Semantic search is not enabled for this service.
        Code: SemanticQueriesNotAvailable
        Message: Semantic search is not enabled for this service.
```
