### ISSUE TITLE
[BUG] conda: error: argument COMMAND: invalid choice: 'activate'

### ISSUE THREAD

**Issue by guybartal** [microsoft/rag-experiment-accelerator#334]
According to [README.md#1-local-install](https://github.com/microsoft/rag-experiment-accelerator/blob/development/README.md#1-local-install) running `conda activate rag-test` results with an error:

> usage: conda [-h] [--no-plugins] [-V] COMMAND ...
> conda: error: argument COMMAND: invalid choice: 'activate' (choose from 'clean', 'compare', 'config', 'create', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'skeleton', 'repo', 'verify', 'token', 'pack', 'env', 'server')

A solution for that should be:

```
conda create -n rag-test python=3.11
conda init bash
# close your terminal in vscode, open a new one and type:
conda activate rag-test
pip install .
```

**Comment by ross-p-smith** [comment]
If you are using a devcontainer - you don't need conda at all now

**Comment by yuvalyaron** [comment]
@ross-p-smith the README provides 2 ways to run the project
1. using a  [dev container](https://github.com/microsoft/rag-experiment-accelerator/blob/development/README.md#1-run-within-a-development-container) as you mentioned
2. running locally (not using a dev container)

The commands in this issue are taken from the section of the 2nd option
