### ISSUE TITLE
Consistent field naming in class Config

### ISSUE THREAD

**Issue by tanya-borisova** [microsoft/rag-experiment-accelerator#406]
This concerns [class Config in rag_experiment_accelerator/config/config.py](https://github.com/microsoft/rag-experiment-accelerator/blob/development/rag_experiment_accelerator/config/config.py).

Most fields of the class are named in CAPS (e.g. `config.CHUNK_SIZES`), where others are in snake case (e.g. `config.data_dir`).

Refactor the fields so that their names are consistent, suggest using snake case everywhere as in PEP-8.

**Comment by julia-meshcheryakova** [comment]
Fixed within #660
