### ISSUE TITLE
Load Documents into the Accelerator in parallel

### ISSUE THREAD

**Issue by raymond-nassar** [microsoft/rag-experiment-accelerator#9]
Parallel jobs need to be enabled within the Accelerator to accept the ingestion and processing of multiple documents/artifacts.

Potential pattern to be applied would be via the implementation of [Azure Machine Learning pipelines](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-parallel-job-in-pipeline?view=azureml-api-2&tabs=cliv2).
```[tasklist]
### Tasks
```

**Comment by Lep06fg** [comment]
done
